server:
  assets-path: /app/assets

theme:
  # Note: assets are cached by the browser, changes to the CSS file
  # will not be reflected until the browser cache is cleared (Ctrl+F5)
  #custom-css-file: /assets/user.css
  background-color: 229 19 23
  contrast-multiplier: 1.2
  primary-color: 222 74 74
  positive-color: 96 44 68
  negative-color: 359 68 71

pages:
  # It's not necessary to create a new file for each page and include it, you can simply
  # put its contents here, though multiple pages are easier to manage when separated
  !include: home.yml
  !include: social.yml
  !include: monitor.yml
  !include: markets.yml
#  !include: experimental.yml

branding: 
  hide-footer: true
  logo-text: Homelab Cabbage
