  - name: Monitor
    center-vertically: true
    columns:
      - size: full
        widgets: 
          - type: search
            autofocus: true

          - type: server-stats
            servers:
              - type: local
                name: homelab-status

          - type: monitor
            cache: 1m
            title: services
            sites:
              - title: Plex
                url: https://plex.homelabcabbage.synology.me
                icon: /assets/plex-logo.png
              - title: Audiobookshelf
                url: https://audiobookshelf.homelabcabbage.synology.me
                icon: /assets/abs-logo.png
              - title: Homelab
                url: https://homelabcabbage.synology.me:5001
                icon: /assets/homelab-logo.png

          - type: docker-containers
            hide-by-default: false

