version: "3.8"

services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    ports:
      - "3005:3000"
    environment:
      SEMAPHORE_DB_DIALECT: sqlite
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: Purplefishland7.
      SEMAPHORE_ADMIN_NAME: "lbailey"
      SEMAPHORE_ADMIN_EMAIL: admin@homelab.local
    volumes:
      - semaphore_data:/var/lib/semaphore
      - ./ansible:/ansible
    restart: unless-stopped

volumes:
  semaphore_data:
