version: "3.8"
services:
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    ports:
      - 32400:32400
    volumes:
      - /volume1/docker/plex:/config
      - /volume1/BIGSHARE/Tv-shows:/tv
      - /volume1/BIGSHARE/Movies:/movies
      - /volume1/BIGSHARE/Music:/music
    restart: unless-stopped
