#Circle Jerks block.  We are handling SSL with Cloudflare 
server {
    listen       		10.0.0.43:443 ssl;
	listen			    127.0.0.1:443 ssl;
    server_name  		www.circle-jerks.net circle-jerks.net;
	error_log 		    /var/log/nginx/circle-jerks.www/error_log;
	access_log 		    /var/log/nginx/circle-jerks.www/access_log;
    root         		/var/www/html/circle-jerks.www;
	ssl_certificate 	/etc/ssl/certs/cloudflare/circle-jerks.pem;
	ssl_certificate_key /etc/ssl/certs/cloudflare/circle-jerks.key;
	http2			    on;
    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;
	include /etc/nginx/ssl_def.conf;


location ~* \.(?:jpg|jpeg|png|ico|gif|svg|mp4|mp3|webm|webp|css|js|woff2?|ttf)$ {
    try_files $uri @circlejerks_www_apache;

    expires 15d;
    add_header Cache-Control "public, immutable";
    add_header Access-Control-Allow-Origin "*";
    include /etc/nginx/includes/cors-sites.conf;
}
location / {
    try_files $uri @circlejerks_www_apache;
}
include /etc/nginx/upstream/circlejerks.www.upstream.conf;
}
